# Generated by Django 5.2 on 2025-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addesk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="название товара"
            ),
        ),
    ]
