# Generated by Django 5.2 on 2025-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addesk", "0002_alter_advert_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advert",
            name="title",
            field=models.CharField(max_length=255, verbose_name="название товара"),
        ),
    ]
